# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'geomorpheye_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 384)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 340, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.rasterLayerLabel = QtWidgets.QLabel(Dialog)
        self.rasterLayerLabel.setGeometry(QtCore.QRect(20, 20, 91, 18))
        self.rasterLayerLabel.setObjectName("rasterLayerLabel")
        self.pushButtonLoad = QtWidgets.QPushButton(Dialog)
        self.pushButtonLoad.setGeometry(QtCore.QRect(20, 260, 371, 34))
        self.pushButtonLoad.setCheckable(False)
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(20, 310, 371, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.rasterLayerCombobox = gui.QgsMapLayerComboBox(Dialog)
        self.rasterLayerCombobox.setGeometry(QtCore.QRect(90, 10, 301, 32))
        self.rasterLayerCombobox.setObjectName("rasterLayerCombobox")
        self.viewFlowCheckbox = QtWidgets.QCheckBox(Dialog)
        self.viewFlowCheckbox.setGeometry(QtCore.QRect(30, 60, 211, 22))
        self.viewFlowCheckbox.setChecked(True)
        self.viewFlowCheckbox.setObjectName("viewFlowCheckbox")
        self.viewPitsCheckbox = QtWidgets.QCheckBox(Dialog)
        self.viewPitsCheckbox.setGeometry(QtCore.QRect(30, 90, 171, 22))
        self.viewPitsCheckbox.setChecked(True)
        self.viewPitsCheckbox.setObjectName("viewPitsCheckbox")
        self.viewColorsCheckbox = QtWidgets.QCheckBox(Dialog)
        self.viewColorsCheckbox.setGeometry(QtCore.QRect(30, 120, 181, 22))
        self.viewColorsCheckbox.setObjectName("viewColorsCheckbox")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(30, 190, 255, 34))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.viewValuesCheckbox = QtWidgets.QCheckBox(self.widget)
        self.viewValuesCheckbox.setObjectName("viewValuesCheckbox")
        self.horizontalLayout.addWidget(self.viewValuesCheckbox)
        self.fontSizeSpinBox = QtWidgets.QSpinBox(self.widget)
        self.fontSizeSpinBox.setObjectName("fontSizeSpinBox")
        self.horizontalLayout.addWidget(self.fontSizeSpinBox)
        self.fontSizeLabel = QtWidgets.QLabel(self.widget)
        self.fontSizeLabel.setObjectName("fontSizeLabel")
        self.horizontalLayout.addWidget(self.fontSizeLabel)
        self.widget1 = QtWidgets.QWidget(Dialog)
        self.widget1.setGeometry(QtCore.QRect(30, 150, 259, 30))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.viewBordersCheckbox = QtWidgets.QCheckBox(self.widget1)
        self.viewBordersCheckbox.setObjectName("viewBordersCheckbox")
        self.horizontalLayout_2.addWidget(self.viewBordersCheckbox)
        self.cellBorderColorButton = gui.QgsColorButton(self.widget1)
        self.cellBorderColorButton.setObjectName("cellBorderColorButton")
        self.horizontalLayout_2.addWidget(self.cellBorderColorButton)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.rasterLayerLabel.setText(_translate("Dialog", "Raster"))
        self.pushButtonLoad.setText(_translate("Dialog", "Load On-Screen Raster Info"))
        self.viewFlowCheckbox.setText(_translate("Dialog", "view steepest direction"))
        self.viewPitsCheckbox.setText(_translate("Dialog", "view sinks"))
        self.viewColorsCheckbox.setText(_translate("Dialog", "view local colormap"))
        self.viewValuesCheckbox.setText(_translate("Dialog", "view raster values"))
        self.fontSizeLabel.setText(_translate("Dialog", "font size"))
        self.viewBordersCheckbox.setText(_translate("Dialog", "view cell borders"))
from qgis import gui
