# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rasterfromvectorfieldloader_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 236)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(50, 200, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 18))
        self.label.setObjectName("label")
        self.lineEditRasterFolder = QtWidgets.QLineEdit(Dialog)
        self.lineEditRasterFolder.setGeometry(QtCore.QRect(110, 10, 241, 32))
        self.lineEditRasterFolder.setObjectName("lineEditRasterFolder")
        self.pushButtonBrowse = QtWidgets.QPushButton(Dialog)
        self.pushButtonBrowse.setGeometry(QtCore.QRect(360, 10, 31, 34))
        self.pushButtonBrowse.setObjectName("pushButtonBrowse")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 81, 16))
        self.label_2.setObjectName("label_2")
        self.lineEditFieldName = QtWidgets.QLineEdit(Dialog)
        self.lineEditFieldName.setGeometry(QtCore.QRect(110, 50, 281, 32))
        self.lineEditFieldName.setObjectName("lineEditFieldName")
        self.pushButtonLoad = QtWidgets.QPushButton(Dialog)
        self.pushButtonLoad.setGeometry(QtCore.QRect(20, 100, 371, 34))
        self.pushButtonLoad.setObjectName("pushButtonLoad")
        self.progressBar = QtWidgets.QProgressBar(Dialog)
        self.progressBar.setGeometry(QtCore.QRect(20, 150, 371, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Raster folder"))
        self.pushButtonBrowse.setText(_translate("Dialog", "..."))
        self.label_2.setText(_translate("Dialog", "Name field"))
        self.pushButtonLoad.setText(_translate("Dialog", "Load Rasters from selected Features"))
