# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'feature-navigator_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Feature Navigator")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 260, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.vectorComboSelector = gui.QgsMapLayerComboBox(Dialog)
        self.vectorComboSelector.setGeometry(QtCore.QRect(10, 50, 261, 31))
        self.vectorComboSelector.setObjectName("vectorComboSelector")
        self.vectorComboLabel = QtWidgets.QLabel(Dialog)
        self.vectorComboLabel.setGeometry(QtCore.QRect(10, 20, 301, 23))
        self.vectorComboLabel.setObjectName("vectorComboLabel")
        self.featureCountTitle = QtWidgets.QLabel(Dialog)
        self.featureCountTitle.setGeometry(QtCore.QRect(10, 90, 211, 23))
        self.featureCountTitle.setObjectName("featureCountTitle")
        self.featureCountValue = QtWidgets.QLabel(Dialog)
        self.featureCountValue.setGeometry(QtCore.QRect(240, 90, 71, 23))
        self.featureCountValue.setObjectName("featureCountValue")
        self.currentFeatureTitle = QtWidgets.QLabel(Dialog)
        self.currentFeatureTitle.setGeometry(QtCore.QRect(10, 120, 201, 23))
        self.currentFeatureTitle.setObjectName("currentFeatureTitle")
        self.currentFeatureValue = QtWidgets.QLabel(Dialog)
        self.currentFeatureValue.setGeometry(QtCore.QRect(240, 120, 71, 23))
        self.currentFeatureValue.setObjectName("currentFeatureValue")
        self.previousButton = QtWidgets.QPushButton(Dialog)
        self.previousButton.setGeometry(QtCore.QRect(10, 190, 181, 33))
        self.previousButton.setObjectName("previousButton")
        self.nextButton = QtWidgets.QPushButton(Dialog)
        self.nextButton.setGeometry(QtCore.QRect(200, 190, 191, 33))
        self.nextButton.setObjectName("nextButton")
        self.loadLayerButton = QtWidgets.QPushButton(Dialog)
        self.loadLayerButton.setGeometry(QtCore.QRect(278, 50, 111, 33))
        self.loadLayerButton.setObjectName("loadLayerButton")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.vectorComboLabel.setText(_translate("Dialog", "Select the vector map to navigate"))
        self.featureCountTitle.setText(_translate("Dialog", "Total features count:"))
        self.featureCountValue.setText(_translate("Dialog", "0"))
        self.currentFeatureTitle.setText(_translate("Dialog", "Current zoomed feature:"))
        self.currentFeatureValue.setText(_translate("Dialog", "0"))
        self.previousButton.setText(_translate("Dialog", "previous"))
        self.nextButton.setText(_translate("Dialog", "next"))
        self.loadLayerButton.setText(_translate("Dialog", "Load"))
from qgis import gui
